version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm run build
            - run: npm run semantic-release
workflows:
  build-and-publish:
    jobs:
      - build-and-publish:
          context: npm
          filters:
            branches:
              only:
                - next
                - master
