name: Lint PR

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: amannn/action-semantic-pull-request@v3.4.0
      with:
        requireScope: false
        validateSingleCommit: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
